apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  namespace: default
  annotations:
    backstage.io/managed-by-location: msgraph:default/fecb2c8a-4c73-4878-96fe-1c741716b365
    backstage.io/managed-by-origin-location: msgraph:default/fecb2c8a-4c73-4878-96fe-1c741716b365
    graph.microsoft.com/group-id: fecb2c8a-4c73-4878-96fe-1c741716b365
  name: pedrogoc_git
  description: test for pedro - CreatedBy DEVGoC
  external:
    type: azure-ad/group
    id: fecb2c8a-4c73-4878-96fe-1c741716b365
  uid: ebe5ce61-2672-4566-a9ee-33b5ebb0f732
  etag: 0441944f1e59041ce90ad55a173509e4c18e9636
relations:
  - type: childOf
    targetRef: group:default/tenaris
    target:
      kind: group
      namespace: default
      name: tenaris
  - type: hasMember
    targetRef: user:default/mdufour_tenaris.com
    target:
      kind: user
      namespace: default
      name: mdufour_tenaris.com
spec:
  type: team
  profile:
    displayName: pedrogoc_git
  children: []
  parent: group:default/tenaris
